server:
  port: 8089

spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/API?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xiaoyu127
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8

  #Swagger配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# mybatis-plus配置
mybatis-plus:
  # xml文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.example.com.example.library.pojo
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名转换
