server:
  port: 8089

spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-2k057qd6.sql.tencentcdb.com:21284/lms?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: Hrk2021123

  #Swagger配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
